[package]
name = "pyo3-bug"
version = "0.1.0"
authors = ["hengchu <hengchu.zhang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3.git"
